#
# Vivado (TM) v2016.2 (64-bit)
#
# create_yarr_on_kc705_project.tcl: Tcl script for re-creating project 'Yarr_FEI4_KC705'
#
# Generated by Vivado on Mon Apr 09 21:28:50 JST 2018
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_yarr_on_kc705_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_pkg.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_disp.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut_base.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_bram.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_rtl.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_top.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/gn4124_core_pkg.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller_wb_slave.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/l2p_fifo.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/generic_async_fifo_wrapper.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/data_alignment.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/cdr_serdes.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_wrapper.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/synchronizer.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/tx-core/serial_port.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core_pkg.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/common_pkg.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/p2l_decoder.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/p2l_dma_master.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/l2p_dma_master.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/l2p_arbiter.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/wbmaster32.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/tx-core/trigger_unit.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/tx-core/tx_channel.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/fei4_rx_channel.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/rr_arbiter.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/trigger-logic/eudet_tlu.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_write_core.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_read_core.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/simple_counter.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/wb_addr_decoder.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/common/k_dual_bram.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/tx-core/wb_tx_core.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/wb_rx_core.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/rx-core/wb_rx_bridge.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/trigger-logic/wb_trigger_logic.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_ctrl_wb.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/xpressk7/app_pkg.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/xpressk7/app.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/kc705/ddr3_yarr_kc705.vhd"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_b.prj"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_a.prj"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/clk_gen/clk_gen.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/fifo_29x32/fifo_29x32.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/fifo_64x512/fifo_64x512.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/fifo_8x32/fifo_8x32.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/fifo_96x512_1/fifo_96x512.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/l2p_fifo64/l2p_fifo64.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/pcie_7x_0/pcie_7x_0.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/ip-cores/kintex7/mig_7series_0_kc705/mig_7series_0.xci"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/kc705/constrs_kc705_ddr3.xdc"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/kc705/constrs_kc705.xdc"
#    "/home/hirose/work/KC705/TestSetup2/Yarr-fw/syn/kc705/constrs_kc705_fmccard-fei4b-osaka.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_yarr_on_kc705_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/Yarr_FEI4_KC705"]"

# Create project
create_project Yarr_FEI4_KC705 ./Yarr_FEI4_KC705 -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects Yarr_FEI4_KC705]
set_property "board_part" "xilinx.com:kc705:part0:1.3" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_pkg.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_disp.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut_base.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_bram.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_rtl.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_top.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/gn4124_core_pkg.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller_wb_slave.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/l2p_fifo.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/generic_async_fifo_wrapper.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/data_alignment.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/cdr_serdes.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_wrapper.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/synchronizer.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/tx-core/serial_port.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core_pkg.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/common_pkg.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/p2l_decoder.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/p2l_dma_master.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/l2p_dma_master.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/l2p_arbiter.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/wbmaster32.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/tx-core/trigger_unit.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/tx-core/tx_channel.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/fei4_rx_channel.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/rr_arbiter.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/trigger-logic/eudet_tlu.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_write_core.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_read_core.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/simple_counter.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/wb_addr_decoder.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/common/k_dual_bram.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/tx-core/wb_tx_core.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/wb_rx_core.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/wb_rx_bridge.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/trigger-logic/wb_trigger_logic.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_ctrl_wb.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/syn/xpressk7/app_pkg.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/syn/xpressk7/app.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/syn/kc705/ddr3_yarr_kc705.vhd"]"\
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_b.prj"]"\
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_a.prj"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_disp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut_base.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_bram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_rtl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/gn4124_core_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller_wb_slave.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/l2p_fifo.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/generic_async_fifo_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/data_alignment.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/cdr_serdes.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/synchronizer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/tx-core/serial_port.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/common_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/p2l_decoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/p2l_dma_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/l2p_dma_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/l2p_arbiter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/wbmaster32.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/tx-core/trigger_unit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/tx-core/tx_channel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/fei4_rx_channel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/rr_arbiter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/trigger-logic/eudet_tlu.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_write_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_read_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/simple_counter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/wb_addr_decoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/common/k_dual_bram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/tx-core/wb_tx_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/wb_rx_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/rx-core/wb_rx_bridge.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/trigger-logic/wb_trigger_logic.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_ctrl_wb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/syn/xpressk7/app_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/syn/xpressk7/app.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/Yarr-fw/syn/kc705/ddr3_yarr_kc705.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top_level" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/clk_gen/clk_gen.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/fifo_29x32/fifo_29x32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/fifo_64x512/fifo_64x512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/fifo_8x32/fifo_8x32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/fifo_96x512_1/fifo_96x512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/l2p_fifo64/l2p_fifo64.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/pcie_7x_0/pcie_7x_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/Yarr-fw/ip-cores/kintex7/mig_7series_0_kc705/mig_7series_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_ddr3.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_ddr3.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_fmccard-fei4b-osaka.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/Yarr-fw/syn/kc705/constrs_kc705_fmccard-fei4b-osaka.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "top_level" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:Yarr_FEI4_KC705"
